### ISSUE TITLE
Image subject category

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#5] opened 2014-12-09 20:50 UTC
This is the ABCD MultiMedia Context and the IEPT, and hence Audubon Core, CVTerm. This element is very important, and should be required as part of image metadata, because, at the most basic level, it allows to separate images that do have the plant or part of the plant in it from images that do not (for example images of labels). According to Audubon Core (http://terms.tdwg.org/wiki/Audubon_Core_Term_List#Iptc4xmpExt:CVterm) we can either choose terms from one or more Audubon Core recommended vocabularies, or come up with a custom vocabulary. At MEL, we have so far come up with the following list, which we use in our collections database:
* Illustration
* SEM
* Label
* Contents of fragment pocket
* Insect damage
* Annotation
* Habit
* Plant detail
* Entire specimen
* Habitat
* Field description
* Unmounted specimen
* Micrograph (not sure how we could let that word creep in)

**Comment by AaronWilton** [comment] 2015-03-05 21:09
At CHR we use the following tags against images that relate to this field, except probably the context ones.  I think some of these need to be included e.g., we have specimens that are linked to photographs of floral visitors (reproductive biology).  

Subject: anatomy, morphology, molecular, pollen, seed, fruit, chromosome, history, reproductive biology, phylogeny, ecology
Object: painting, drawing, specimen, photo slide, microscopic slide, photograph, type specimen
Context: in situ, ex situ, laboratory, glasshouse, field, cultivation

**Comment by nielsklazenga** [comment] 2015-03-06 01:36
Yes, the list I gave is just what we use in our collections database at the moment and we haven't had images in our database very long, so it is bound to be incomplete. Was never meant to be __the__ vocabulary, just a start.

**Comment by nielsklazenga** [comment] 2015-06-14 08:22
Also, some of the terms in our (MEL's) list are [`ac:subtypeLiteral`](http://terms.tdwg.org/wiki/Audubon_Core_Term_List#ac:subtypeLiteral), not [`Iptc4xmpExt:CVterm`](http://terms.tdwg.org/wiki/Audubon_Core_Term_List#Iptc4xmpExt:CVterm).

**Comment by AaronWilton** [comment] 2016-02-10 23:41
Reading the AC wiki [here](http://terms.tdwg.org/wiki/AC_Subtype_Examples) it appears that ac:subtype is in intended to refine dc:type properties rather than specialisation of subject category.

I will put together a vocabulary based on our lists above that can be refined in future versions.

**Comment by AaronWilton** [comment] 2016-02-11 02:36
draft: 
```xml
<concept dc:identifier="illustration" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/illustration" dc:description="illustration" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="illustration"/>
		</preferred>
	</concept>
	<concept dc:identifier="painting" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/painting" dc:description="painting" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="painting"/>
		</preferred>
	</concept>
	<concept dc:identifier="drawing" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/drawing" dc:description="drawing" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="drawing"/>
		</preferred>
	</concept>
	<concept dc:identifier="in situ" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/in-situ" dc:description="in situ" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="in situ"/>
		</preferred>
	</concept>
	<concept dc:identifier="ex situ" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/ex-situ" dc:description="image depicts subject in staged setting outside of place where it was growing" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="ex situ"/>
		</preferred>
	</concept>
	<concept dc:identifier="laboratory" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/laboratory" dc:description="laboratory" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="laboratory"/>
		</preferred>
	</concept>
	<concept dc:identifier="cultivation" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/cultivation" dc:description="cultivation" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="cultivation"/>
		</preferred>
	</concept>
	<concept dc:identifier="label" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/label" dc:description="label" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="label"/>
		</preferred>
	</concept>
	<concept dc:identifier="insect damage" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/insect-damage" dc:description="Insect damage" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="insect damage"/>
		</preferred>
	</concept>
	<concept dc:identifier="annotation" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/annotation" dc:description="Annotation" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="annotation"/>
		</preferred>
	</concept>
	<concept dc:identifier="field description" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/field+description" dc:description="field description" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="field description"/>
		</preferred>
	</concept>
	<concept dc:identifier="specimen" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/specimen" dc:description="specimen" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="specimen"/>
		</preferred>
		<alternative>
			<term dc:title="entire specimen"/>
		</alternative>
	</concept>
	<concept dc:identifier="fragment packet" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/fragment+packet" dc:description="contents of a fragment packet" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="fragment packet"/>
		</preferred>
	</concept>
	<concept dc:identifier="habit" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/habit" dc:description="habit" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="habit"/>
		</preferred>
	</concept>
	<concept dc:identifier="habitat" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/habitat" dc:description="habitat" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="habitat"/>
		</preferred>
	</concept>
	<concept dc:identifier="plant detail" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/plant+detail" dc:description="plant detail" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="plant detail"/>
		</preferred>
	</concept>
	<concept dc:identifier="anatomy" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/anatomy" dc:description="anatomy" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="anatomy"/>
		</preferred>
	</concept>
	<concept dc:identifier="morphology" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/morphology" dc:description="morphology" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="morphology"/>
		</preferred>
	</concept>
	<concept dc:identifier="pollen" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/pollen" dc:description="pollen" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="pollen"/>
		</preferred>
	</concept>
	<concept dc:identifier="seed" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/seed" dc:description="seed" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="seed"/>
		</preferred>
	</concept>
	<concept dc:identifier="spore print" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/spore+print" dc:description="spore print" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="spore print"/>
		</preferred>
	</concept>
	<concept dc:identifier="fruit" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/fruit" dc:description="fruit" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="fruit"/>
		</preferred>
	</concept>
	<concept dc:identifier="chromosome" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/chromosome" dc:description="chromosome" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="chromosome"/>
		</preferred>
	</concept>
	<concept dc:identifier="reproductive biology" dc:URI="http://hiscom.chah.org.au/hispid/vocabulary/subject_category/reproductive+biology" dc:description="reproductive biology" dc:issued="2015-10-23">
		<preferred>
			<term dc:title="reproductive biology"/>
		</preferred>
	</concept>
```

**Comment by nielsklazenga** [comment] 2016-02-11 04:46
Yes, that (two comments back)'s what I mean. 'SEM' is `ac:subtypeLiteral` (or there was imaging technique somewhere, I think), not `iptc4xmp:Cvterm. So are 'drawing', 'painting' etc.

**Comment by AaronWilton** [comment] 2016-02-14 22:19
yes, wasn't sure what to do with SEM (I think that would fit better in subtype) - so have omitted here, however I think that it is valid to have an image that has the content of a drawing or painting so I think they fit here well.

**Comment by nielsklazenga** [comment] 2016-02-15 01:24
'painting' and 'illustration' are definitely ac:subtype. See: http://terms.tdwg.org/wiki/AC_Subtype_Examples.

**Comment by AaronWilton** [comment] 2016-02-15 01:57
yes, I am not disagreeing that they are in that vocabulary but I do not those think the vocabularies for those terms need to be (or will be) mutually exclusive

To me this is dictated by which property is appropriate to use, which depends entirely on what the electronic record is describing:
- subtype would be appropriate when the electronic record (metadata) is for a **painting** e.g., the electronic record is an entry in a catalogue for a painting
- subject/content when the electronic record is the metadata for an **image** that depicts a painting

I can see us more commonly using the second case than the first...

**Comment by AaronWilton** [comment] 2016-03-21 02:50
no additional comments so closing ;-)

**Closed by AaronWilton** 2016-03-21 02:50 UTC
Labels: ACTION, images, Teleconference 2016-02
